stages:
  - name: lint
    if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
  - name: compile
    if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
  - name: test
    if: branch = master OR branch =~ ^\d+\.\d+\.\d+$
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$
jobs:
  include:
    - stage: compile
      env: SWIFT_BUILD_VERSION=5 SWIFT_VERSION=5.0-DEVELOPMENT-SNAPSHOT-2019-01-13-a
      name: Linux / Swift 3.2
      os: linux
      dist: trusty
      sudo: required
      language: generic
      before_install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      install: swift build -Xswiftc -swift-version -Xswiftc $SWIFT_BUILD_VERSION
      script: "true"
